import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Image, Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { WebView } from 'react-native-webview';
import ScreenShell, { colors } from '../components/ScreenShell';
import { loadSubcontractorSiteWalk360, subcontractorMediaUrl } from '../api/subcontractorApi';
const TAGS = ['All', 'Antenna', 'Node', 'Cores', 'Miscellaneous', 'IDF / ER', 'Electrical'];
const clean = (v) => String(v ?? '').trim();
const siteName = (project) => clean(project?.site_name || project?.name || project?.label || project);
const media = (portalUrl, p) => subcontractorMediaUrl(portalUrl, p?.thumb_url || p?.public_url || p?.url || p?.image_url);
const full = (portalUrl, p) => subcontractorMediaUrl(portalUrl, p?.public_url || p?.url || p?.image_url || p?.thumb_url);
function viewerHtml(imageUrl) { return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><style>html,body{margin:0;height:100%;background:#020617;color:white;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}#pano{width:100%;height:100%;object-fit:cover;transition:transform .05s linear;transform-origin:center center}#help{position:fixed;left:12px;right:12px;bottom:12px;padding:10px 12px;border-radius:16px;background:rgba(2,6,23,.68);font-weight:800;font-size:13px;text-align:center}</style></head><body><img id="pano" src="${String(imageUrl||'').replace(/"/g,'&quot;')}"/><div id="help">Drag left/right to look around. Pinch zoom is handled by the device image viewer.</div><script>let x=0,sx=0,down=false;const img=document.getElementById('pano');function draw(){img.style.transform='translateX('+x+'px) scale(1.22)'}addEventListener('pointerdown',e=>{down=true;sx=e.clientX});addEventListener('pointermove',e=>{if(!down)return;x+=(e.clientX-sx)*.45;sx=e.clientX;if(x>innerWidth/2)x=-innerWidth/2;if(x<-innerWidth/2)x=innerWidth/2;draw()});addEventListener('pointerup',()=>down=false);draw();</script></body></html>`; }
export default function SubcontractorSiteWalk360Screen({ session, project, onBack, onHome }) {
  const { width } = useWindowDimensions(); const columns = width >= 980 ? 3 : width >= 680 ? 2 : 1;
  const [loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[sitewalks,setSitewalks]=useState([]),[selectedSitewalk,setSelectedSitewalk]=useState(''),[tag,setTag]=useState('All'),[query,setQuery]=useState(''),[items,setItems]=useState([]),[selected,setSelected]=useState(null);
  const selectedSite=siteName(project);
  const load=useCallback(async({silent=false}={})=>{ if(!selectedSite)return; if(!silent)setLoading(true); try{ const data=await loadSubcontractorSiteWalk360(session.portalUrl,session.access_token,{siteName:selectedSite,sitewalk:selectedSitewalk,tag,q:query}); const walks=Array.isArray(data?.sitewalks)?data.sitewalks:[]; setSitewalks(walks); if(!selectedSitewalk&&walks.length)setSelectedSitewalk(clean(walks[0]?.value||walks[0]?.sitewalk_desc||walks[0])); setItems(Array.isArray(data?.items)?data.items:[]);}catch(e){Alert.alert('SiteWalk 360',e?.message||'Unable to load SiteWalk 360 photos.')}finally{setLoading(false);setRefreshing(false)}},[session?.portalUrl,session?.access_token,selectedSite,selectedSitewalk,tag,query]);
  useEffect(()=>{load()},[load]); const refresh=()=>{setRefreshing(true);load({silent:true})}; const data=useMemo(()=>items,[items]);
  return <ScreenShell title="SiteWalk 360 Photos" subtitle={selectedSite} onBack={onBack} onHome={onHome}><View style={styles.wrap}><View style={styles.toolbarCard}><TextInput value={query} onChangeText={setQuery} placeholder="Search 360 photos" placeholderTextColor="#71839b" style={styles.search} returnKeyType="search" onSubmitEditing={()=>load({silent:true})}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{sitewalks.map((walk,idx)=>{const value=clean(walk?.value||walk?.sitewalk_desc||walk)||`SiteWalk ${idx+1}`;return <Pressable key={`${value}-${idx}`} onPress={()=>setSelectedSitewalk(value)} style={[styles.chip,selectedSitewalk===value&&styles.chipActive]}><Text style={[styles.chipText,selectedSitewalk===value&&styles.chipTextActive]}>{value}</Text></Pressable>})}</ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{TAGS.map(v=><Pressable key={v} onPress={()=>setTag(v)} style={[styles.tag,tag===v&&styles.tagActive]}><Text style={[styles.tagText,tag===v&&styles.tagTextActive]}>{v}</Text></Pressable>)}</ScrollView></View>{loading?<View style={styles.center}><ActivityIndicator color={colors.blue}/><Text style={styles.muted}>Loading 360 photos…</Text></View>:<FlatList data={data} key={columns} numColumns={columns} keyExtractor={(item,index)=>String(item?.id||index)} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentContainerStyle={styles.list} renderItem={({item})=><Pressable style={[styles.cardWrap,{width:`${100/columns}%`}]} onPress={()=>setSelected(item)}><View style={styles.photoCard}>{media(session.portalUrl,item)?<Image source={{uri:media(session.portalUrl,item)}} style={styles.thumb}/>:<View style={[styles.thumb,styles.noImage]}><Text style={styles.noImageText}>360</Text></View>}<View style={styles.cardBody}><Text style={styles.photoTitle} numberOfLines={2}>{clean(item?.name||item?.caption||item?.file_name)||'360 Photo'}</Text><Text style={styles.meta} numberOfLines={1}>{clean(item?.tag)||'Untagged'}{clean(item?.sitewalk_desc)?` · ${clean(item.sitewalk_desc)}`:''}</Text></View></View></Pressable>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No 360 photos found</Text><Text style={styles.muted}>This shows only allowed SiteWalk 360 photos for this subcontractor project.</Text></View>}/>}</View><Modal visible={!!selected} animationType="slide" onRequestClose={()=>setSelected(null)}><ScreenShell title="360 Viewer" subtitle={clean(selected?.name||selected?.caption||selected?.file_name)} onBack={()=>setSelected(null)} onHome={onHome}><WebView originWhitelist={['*']} source={{html:viewerHtml(full(session.portalUrl,selected))}} javaScriptEnabled domStorageEnabled style={{flex:1,backgroundColor:'#020617'}}/></ScreenShell></Modal></ScreenShell>
}
const styles=StyleSheet.create({wrap:{flex:1},toolbarCard:{margin:12,padding:12,borderRadius:22,backgroundColor:'rgba(255,255,255,.92)',borderWidth:1,borderColor:colors.line,gap:10},search:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.line,borderRadius:16,paddingHorizontal:14,paddingVertical:11,color:colors.text,fontWeight:'800'},chips:{gap:8,paddingRight:8},chip:{paddingHorizontal:12,paddingVertical:9,borderRadius:999,backgroundColor:'#eef6ff',borderWidth:1,borderColor:'#c8def6'},chipActive:{backgroundColor:'#10233f',borderColor:'#10233f'},chipText:{fontWeight:'900',color:'#31506d'},chipTextActive:{color:'#fff'},tag:{paddingHorizontal:11,paddingVertical:8,borderRadius:999,backgroundColor:'#fff',borderWidth:1,borderColor:colors.line},tagActive:{backgroundColor:colors.blue,borderColor:colors.blue},tagText:{fontWeight:'900',color:colors.muted},tagTextActive:{color:'#fff'},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10},muted:{color:colors.muted,fontWeight:'800',textAlign:'center'},list:{padding:8,paddingBottom:30},cardWrap:{padding:6},photoCard:{backgroundColor:'#fff',borderRadius:18,borderWidth:1,borderColor:colors.line,overflow:'hidden',shadowColor:'#0f172a',shadowOpacity:.06,shadowRadius:10,shadowOffset:{width:0,height:5},elevation:2},thumb:{width:'100%',aspectRatio:1.72,backgroundColor:'#dbe7f2'},noImage:{alignItems:'center',justifyContent:'center'},noImageText:{color:colors.blue,fontWeight:'900',fontSize:30},cardBody:{padding:12},photoTitle:{color:colors.text,fontWeight:'900',fontSize:15,lineHeight:20},meta:{marginTop:5,color:colors.muted,fontWeight:'800',fontSize:12},empty:{padding:26,alignItems:'center'},emptyTitle:{fontSize:18,fontWeight:'900',color:colors.text,marginBottom:6}})
